### ISSUE TITLE
Right aligned menus

### ISSUE THREAD

**Issue by mguinness** [owenversteeg/min#64]
I'm trying to emulate navbar-right class in bootstrap to right align some menu items.  The following appears to work, but is there a better way to do this?

``` css
@media screen and (min-width: 500px) {
  .nav-right {
    float: right;
    padding-top: 7px;
  }
}
```

``` html
<span class="nav-right">
  <a href="#">Register</a>
  <a href="#">Log in</a>
</span>
```
